language: python
python:
  - '2.7'
env:
  - PGVERSION=9.2
dist: trusty
sudo: required
cache: pip
install:
  - bash bin/travis-build.bash
  - pip install coveralls
script: sh bin/travis-run.sh
after_success:
  - coveralls
